services:
  unused_items_backend:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - ui_db
    restart: on-failure
    volumes:
      - ../unused-items:/app
    networks:
      ui_network:

  ui_db:
    image: postgres:14-alpine
    volumes:
      - db_volumes:/var/lib/postgresql/data
    env_file:
      - ./env/.env
    ports:
      - 5432:5432
    networks:
      ui_network:

volumes:
  db_volumes:

networks:
  ui_network:
    driver: bridge

