# Generated by Django 4.1.2 on 2022-10-28 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('decription', models.TextField(max_length=1000)),
                ('type', models.CharField(choices=[('Fundacja', 'Fundation'), ('Organizacja Pozarządowa', 'Ngo'), ('Zbiórka Lokalna', 'Local Collection')], default='Fundacja', max_length=25)),
                ('categories', models.ManyToManyField(related_name='instotution_categories', to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=50)),
                ('pick_up_date', models.DateTimeField()),
                ('pick_up_time', models.TimeField()),
                ('pick_up_comment', models.TextField(max_length=500)),
                ('categories', models.ManyToManyField(related_name='dontaion_categories', to='home.category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='home.institution')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
